baseURL = "https://simonensemble.github.io/hugo_website"
theme = "cactus"
languageCode = 'en-us'
title = 'The Simon Research Ensemble'
enableEmoji = true
[params]
  colortheme = "white" # dark, light, white, or classic
  description = "we are a mathematical and computational research group at Oregon State University, in the School of Chemical, Biological, and Environmental Engineering."
  mainSectionTitle = " "
  showAllPostsOnHomePage = false
  showAllPostsArchive = true
  postsOnHomePage = 0
  css = ["css/custom.css"]
  logo="trees.png"
  mathjax = true 
  [params.comments]
    enabled = true
    disqusShortname = "CoryMSimon"

# Main menu which appears below site header.
[[menu.main]]
name = "students"
url = "/students"
weight = 1

[[menu.main]]
name = "pubs"
url = "/pubs"
weight = 2

[[menu.main]]
name = "the prof"
url = "/theprof"
weight = 3

[[menu.main]]
name = "news"
url = "/news"
weight = 4

[[menu.main]]
name = "teaching"
url = "/teaching"
weight = 5

[[menu.main]]
name = "blog"
url = "/posts"
weight = 6
